# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Web App CI

on:
  push:
    branches: [master]
    paths:
      - 'clients/web-app/**.*'
  pull_request:
    branches: [master]
    paths:
      - 'clients/web-app/**.*'

defaults:
  run:
    working-directory: clients/web-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install --frozen-lockfile
      - run: yarn prettier-check
      - run: yarn test
      - run: yarn build
